### ISSUE TITLE
Needs a LICENSE

### ISSUE THREAD

**Issue by david-a-wheeler** [mayank-ramnani/temper#1]
Hi, I don't see any LICENSE, so the default laws apply (which generally don't allow use).

I'm guessing that you intend for this to be released as open source software. The OpenSSF requires MIT or Apache-2.0 license, and I'm guessing you want to use those. 

E.g., you could copy this into LICENSE.md and add the year and your name:
https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md

**Comment by mayank-nyu** [comment]
Added. Thank you!
(https://github.com/mayank-ramnani/temper/blob/main/LICENSE.md)
